### ISSUE TITLE
fix(convertKit): Update hooks for compatibility with Give 2.1

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/Give-ConvertKit#7]
## Issue Overview
As a Give Admin, I want to use Give ConvertKit in a way that is consistent with Give 2.1, so that I don't have any PHP warnings from deprecated hooks in the plugin.

Deprecated hooks were announced here:
https://developers.givewp.com/2018/03/19/legacy-hooks-being-deprecated-within-2-0-7/

## Expected Behavior
There should not be any deprecate hook.

## Current Behavior
Without an update, Give-ConvertKit will have deprecated hooks as of Give 2.1.

# Related Issues 
- https://github.com/WordImpress/Give-Form-Field-Manager/issues/241
- https://github.com/WordImpress/Give-Tributes/issues/245

**Comment by ravinderk** [comment]
@raftaar1191 can you add the list of the deprecated hook which we are using in this plugin?
